# Generated by Django 3.1.4 on 2020-12-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20201209_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(blank=True, choices=[('En', 'English'), ('Ru', 'Russian'), ('Ge', 'German'), ('Fr', 'French')], default='En', help_text="Enter the book's natural language (e.g. English, French, German etc.)", max_length=200),
        ),
    ]
