# Generated by Django 3.1.4 on 2020-12-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20201209_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='languages',
        ),
        migrations.AddField(
            model_name='book',
            name='languages',
            field=models.ManyToManyField(help_text='Select a language for this book', null=True, to='catalog.Language'),
        ),
    ]
