# Generated by Django 3.1.4 on 2020-12-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20201209_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='languages',
            field=models.ManyToManyField(help_text='Select a language for this book', to='catalog.Language'),
        ),
    ]
